export interface MessageItem {
  plid: string; // "88355",
  isnew: string; // "0",
  pmnum: string; // "3",
  lastupdate: string; // "1460867026",
  lastdateline: string; // "1460895733",
  authorid: string; // "35385",
  pmtype: string; // "1",
  subject: string; // "关于您在“闲来无事，用辉光管diy了个台钟。。貌似这东西也挺扫”的帖子\n打扰下~请问您 ...",
  members: string; // "2",
  dateline: string; // "1460895733",
  touid: string; // "35385",
  pmid: string; // "88355",
  lastauthorid: string; // "35385",
  lastauthor: string; // "sttacm",
  lastsummary: string; // "感谢~",
  msgfromid: string; // "35385",
  msgfrom: string; // "sttacm",
  message: string; // "感谢~",
  msgtoid: string; // "35385",
  tousername: string; // "sttacm"
}
